#!/usr/bin/env ruby
require 'Date'

payments_received = [190, 160]
amount_paid = payments_received.inject(&:+)

rent_monthly, utilities_monthly = 1075/2.0, 100/2.0
daily_rent = (rent_monthly + utilities_monthly)*12.0/365

date_arrived = Date.new(2019, 3, 9)
days_passed = Date.today - date_arrived

if ARGV[0]
  days_passed += ARGV[0].to_i
end

remaining_balance = (days_passed*daily_rent) - amount_paid

puts "Daily rent per person is: #{daily_rent}"
puts "Nikhil has paid #{amount_paid} dollars. His remaining balance is, or will be, #{remaining_balance} dollars."